### ISSUE TITLE
RU.MESH.PROP#1 DNS

### ISSUE THREAD

**Issue by whoizit** [russian-meshnet/meshnet-chat-agenda#3]
## Russian Meshnet Propose 1. DNS

- Независимые сервисы-регистраторы доменных имен. У каждого свой git репозиторий.

- Существует единый репозиторий со списком сервисов-регистраторов, подключенных к репозиторию как git submodules.
Который курируется доверенными лицами сообщества. Например в russian-meshnet равные, полные права имею я (whoami), foxcool, kirushik
https://git-scm.com/book/ru/v2/Инструменты-Git-Подмодули

Допустим единый репозиторий будет `github.com/russian-meshnet/dns-subs`
(В последующем, если идея понравится сообществу, то репозиторий переедет под контроль сообщества yggdrasil.)

Каждый сервис-регистратор добавляется по запросу в dns-subs как git submodule

Договариваемся о том, что каждый сервис-регистратор обслуживает только одну зону, например .y, .ygg, .yggdrasil, .h, .z, .k или что угодно. Обязательным требованием является чтобы зона не перекрывала зону в ICANN, OpenNIC. Для этого следует подготовить обновляемый список зон недоступных для использования.

Если кто-то начнет мухлевать, его репозиторий будет исключен из dns-subs

Что нужно реализовать? Веб-сервис для реализации сервис-регистратора. 
Человек регистрируется на сервисе с использованием своей электронной почты и её подтверждением.
В конфиге можно указывать сколько доменных имен может зарегистрировать один человек на одну почту. Допустим это число по дефолту будет 3 (три). Чтобы избежать киберсквоттинга.

Человек в веб-интерфейсе может добавлять, удалять субдомены к каждому домену который он зарегистриует
Веб-сервис отвечает за проверку существует ли в его базе уже это доменное имя, если нет, то он позволяет его зарегистрировать. 
Регистрация доменного имени это просто коммит от имени сервиса в публичный git репозиторий.
Т.к. база будет открытой и исходники сервиса так-же открыты, то в случае если майнтейнер пропадёт, всегда можно будет передать права курирования этой зоны другому человеку изменив запись в dns-subs.
Так-же имеет смысл прямо в этом же репозитории хранить в base64 виде почты юзеров. Формат файла например YAML 
```
d2hvYW1pQHN5c3RlbWxpLm9yZw:
    <ygg-ipv6-1>: whoami.y example1.y proxy.whoami.y hub.whoami.y
    <ygg-ipv6-2>: whatelse.y
```
Логин в сервис происходит без пароля. При нажатии на кнопку логина в веб-сервисе, на указанную почту присылается уникальная одноразовая ссылка для логина. Таким образом не нужно хранить в базе пароли или хеши и можно базу переносить от майнтейнера к другому майнтейнеру.

Предлагаю реализовать подобный сервис на Go, простом языке с великолепной портируемостью. Такой сервис, в теории, можно будет запустить даже на говнороутере.

Любой сможет запустить такой-веб сервис и курировать свою доменную зону.

Простой пользователь сможет использовать dns-subs и скриптом генерировать по крону свой /etc/hosts который не зависит от DNS сервисов
Так-же любой сможет поднимать свой собственный публичный/не публичный DNS сервер

**Comment by ChronosXYZ** [comment]
Можно еще сюда подключить DHT, это как раз подходит для таких вещей.

**Comment by whoizit** [comment]
https://github.com/mwarning/KadNode
https://github.com/torrentkino/torrentkino
https://github.com/cryptostorm/cstorm_deepDNS
https://github.com/ear7h/e7

**Comment by whoizit** [comment]
закрыто в связи с появлением раздела с дискуссиями на гитхабе. Если нужно продолжение - там.
